### ISSUE TITLE
Create a My Location Button to center and zoom the map, as well as an address search field

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/sandiego-food-map#15]
Just like on foodoasis.la, we need a button that centers and zooms the map. Also we need an address search field that does a geocode of the address to lat long.

Both cases should drop a pin at that location and center on it and appropriately zoom.

**Comment by nikolajbaer** [comment]
Here is the example on getting the current location:

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition#examples

e.g. in console:

`navigator.geolocation.getCurrentPosition((e)=>{ console.log(e) });`

**Comment by BolunThompson** [comment]
Merged
