### ISSUE TITLE
Theme the site for San Diego

### ISSUE THREAD

**Issue by BolunThompson** [opensandiego/sandiego-food-map#2]
Currently, this site isn't themed for San Diego. This would be to change the site so it is for San Diego.

This may be a big issue, so feel free to add new issues for specific parts and mention them in the comments of this issue.

**Comment by snajmi** [comment]
![foodoasis-sd-01](https://user-images.githubusercontent.com/1316929/93004782-2dc5d880-f4ff-11ea-9167-426cbf5ec911.png)
Logo for Food Oasis SD site, consistent with Food Oasis California and Food Oasis Los Angeles
