### ISSUE TITLE
Explore whether we can use Github actions for running scripts

### ISSUE THREAD

**Issue by BolunThompson** [opensandiego/sandiego-food-map#49]
We would use Github actions as a replacement for AWS lambda.

Tasks:
- [x] can we store secret tokens for s3 and saleforce

**Comment by pmelendez2** [comment]
Creating SECRET tokens that can be used within GitHub Actions can be easily done.  GitHub -> Repositories -> Settings -> Secrets, example in San Diego Open Voters Voice at least in my fork :).
![SDVV_Secrets](https://user-images.githubusercontent.com/33038363/113919231-39793500-9798-11eb-91e2-97d91556d5cb.png)

**Comment by pmelendez2** [comment]
GitHub -> Repositories -> Settings -> Secrets, example in San Diego Open Voters Voice at least in my fork :).

**Comment by BolunThompson** [comment]
We should be able to use Github actions.
